/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import java.awt.AWTException;
import java.net.MalformedURLException;

public class App {
    public void getGreeting() throws InterruptedException, MalformedURLException, AWTException {
        ImdbRatings tests = new ImdbRatings(); // Initialize your test class
        // Image_URL tests =new Image_URL();
        // BookMyShow tests =new BookMyShow();
        // BookMyShow tests =new BookMyShow();
        // BookMyShow tests =new BookMyShow();

        // TODO: call your test case functions one after other here

        tests.testCase01();

        // END Tests

        tests.endTest(); // End your test by clearning connections and closing
        // browser
    }

    public static void main(String[] args) throws InterruptedException, MalformedURLException, AWTException {
        new App().getGreeting();
    }
}
